### ISSUE TITLE
/docs erroring: Incompatible types in allOf at "#/components/schemas/PostNotificationRule/oneOf/0/properties/labels/items

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#15577]
seeing this error in the /docs page. i think there is an issue in swagger.

![image](https://user-images.githubusercontent.com/4805997/67531490-c0575200-f677-11e9-95ea-7072e0819e5f.png)

**Comment by jademcgough** [comment]
This was introduced by #15305. Should be a quick fix.

**Comment by russorat** [comment]
Is it possible to add a test for the /docs page in the future? If not in this issue, could you open a new one?

**Comment by jademcgough** [comment]
@russorat was thinking the same thing. We should be able to add a swagger verification step to our CI process and fail if it isn't valid openapi spec.

**Comment by russorat** [comment]
this is fixed.
