### ISSUE TITLE
Unable to go get the client package

### ISSUE THREAD

**Issue by monnand** [influxdata/influxdb#756]
The [old client package](https://github.com/influxdb/influxdb-go) is deprecated, and moved to the main repo. This is totally fine to copy the code in another repo, but deleting code in the old repo is _really_ a bad practice. It breaks any existing third party code depends on it.

Even worse, the new client package is not go-get-able:

```
$ go get -u github.com/influxdb/influxdb/client
# github.com/influxdb/influxdb/protocol
influxdb/protocol/protocol_extensions.go:18: undefined: Point
influxdb/protocol/protocol_extensions.go:24: undefined: Point
influxdb/protocol/protocol_extensions.go:28: undefined: Point
influxdb/protocol/protocol_extensions.go:32: undefined: Point
influxdb/protocol/protocol_extensions.go:38: undefined: FieldValue
influxdb/protocol/protocol_extensions.go:63: undefined: Point
influxdb/protocol/protocol_extensions.go:73: undefined: Point
influxdb/protocol/protocol_extensions.go:92: undefined: Request
influxdb/protocol/protocol_extensions.go:96: undefined: Request
influxdb/protocol/protocol_extensions.go:102: undefined: Request
influxdb/protocol/protocol_extensions.go:102: too many errors
```

This makes the transition to new client package a non-trivial work.

Is there any plan to fix this problem?
